services:
  - type: web
    name: frontend
    env: static
    runtime: static
    static_site:
      build_command: pnpm install --no-frozen-lockfile && pnpm run build
      publish_directory: frontend/build
    auto_deploy: true

  - type: web
    name: backend
    env: node
    runtime: node
    build_command: pnpm install
    start_command: node src/index.js
    auto_deploy: true
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASS: ${GMAIL_PASS}
